title: Cuba Weather InsMet Python
description: Application programming interface of the Cuba Weather project for insmet.cu implemented in Python
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
